### ISSUE TITLE
WAB 2.4 support

### ISSUE THREAD

**Issue by g3r4n** [gbochenek/esri-wab-build#10]
The script failed with WAB 2.4 default app.
Console error : 
``` 
TypeError: Cannot read property 'en' of undefined
    at Object.<anonymous> (main.js?wab_dv=2.4:536)
    at Object.forEach (init.js:70)
    at Object.registerWidgetFeatureActions (main.js?wab_dv=2.4:535)
    at Object.<anonymous> (main.js?wab_dv=2.4:536)
    at init.js:63
    at k (main.js?wab_dv=2.4:146)
    at Object.k [as visitElement] (main.js?wab_dv=2.4:146)
    at Object.b.visitElement (main.js?wab_dv=2.4:11)
    at Object.registerAllWidgetFeatureActions (main.js?wab_dv=2.4:536)
    at Object._onAppConfigLoaded (main.js?wab_dv=2.4:538) "TypeError: Cannot read property 'en' of undefined
```

**Comment by g3r4n** [comment]
in prebuild.js the mergeAndWriteWidgetManifests function don't take care of i18n labels of feature actions. I will make a fix as soon as possible.

Quick fix : 
in buildOut\app\widgets\widgets-manifest.json add the default i18n labels like that : 
```
        "i18nLabels_featureAction_ShowRelatedRecords": {
            "defaultLabel": "Show Related Records"
        },
        "i18nLabels_featureAction_ViewInTable": {
            "defaultLabel": "View In Table"
        },
```

**Comment by gbochenek** [comment]
I'd like to add 2.4 support in a way so 2.3 will still work.

We have to be careful as the default build config can change between WAB versions.  I know it did significantly between 2.1 and 2.3.

**Comment by gbochenek** [comment]
Thinking this over and just getting 2.4 to work would be a start, we don't have to make it work with everything right away. Users can still download 0.0.5, vs. 1.0.0 if they're looking for 2.3 support.

**Comment by gbochenek** [comment]
Thanks @g3r4n !

**Comment by crackernutter** [comment]
Thanks!  Tested this with a larger app and most things worked perfectly!  It forced me to correct a couple minor errors in some custom widgets (mostly just commas where they're not necessary).  I also had some problems with my custom header controller, but I suspect this had to do with the upgrade from 2.0.1 to 2.4.  The upgraded custom header controller worked in the 2.4 unbuilt app, but not in the built app.  So I just redid my modifications to the default one installed with 2.4, copied it into my app, and the build process didn't cause any problems from there.  Really appreciate the work you put into this!

**Comment by crackernutter** [comment]
Whoops! Just stumbled on an issue with this: on an app using the foldable theme (for example - I haven't tested other themes), after running esri-wab-build and loading the optimized application, I'm able to load widgets in the header controller just find, but widgets underneath the search bar (I have basemap gallery, bookmarks, draw, and measure) won't load and throw an error.  

404 error for https://gisdev.eon.faa.gov/apps/app/jimu.js/OnScreenWidgetPanel.js?wab_dv=2.4. 

Are you getting this error at all?
