### ISSUE TITLE
Correctly Handle International Applications

### ISSUE THREAD

**Issue by gbochenek** [gbochenek/esri-wab-build#2]
Currently applications built in other locales fail to produce a working application.

Test failed with a Norwegian locale.

**Comment by g3r4n** [comment]
Have a look to addI18NLabel() in utilscripts.js. 
we should create function that will create i18n for every value in nls root object.
related to #10 too.

**Comment by g3r4n** [comment]
I was wrong. Test succeed with French as locale. 
Can you give an example in order to reproduce ?
Did you get an error message or did you get the default string (en) ?

**Comment by gbochenek** [comment]
I think this should be fixed with the latest version.  Will create a new more specific issue if there are continued problems.
