### ISSUE TITLE
no dojo.js output

### ISSUE THREAD

**Issue by jdthoen** [gbochenek/esri-wab-build#35]
[build-report.txt](https://github.com/gbochenek/esri-wab-build/files/1169958/build-report.txt)
I must be doing something wrong.  Everytime I run esri-wab-build it create the folders, creates the zip file but does not create a dojo.js.  The arcgis app\arcgis-js-api is empty.  All js files are removed, which I assume is correct bit I would expect the dojo.js to include them all.  Attached is the build-report against a new app from the web app builder version 2.3.

**Comment by rsjones** [comment]
@Biboba we're working on fixing this. Currently if you aren't using vector tiles you can use the version from my fork and it will give you a fully disconnected build that should work. When we have the webworker issue worked out for vector tiles then the fork will be pulled back into main project and and update will be pushed to npm. Even though the current build isn't fully disconnected it significantly improves performance vs unbuilt with some of the resources still coming from the cdn.

**Comment by Biboba** [comment]
@rjones Great ! Glad to know that somebody is already working on this. 
Thanks for your explanations

**Comment by areedjones** [comment]
You are welcome, but I think you meant to @ rsjones!
