### ISSUE TITLE
Build output error on web app builder 2.5 app

### ISSUE THREAD

**Issue by tmatinde** [gbochenek/esri-wab-build#37]
Created a build using web app builder 2.5

Build was missing jimu.js/OnScreenWidgetIcon and WidgetPlaceholder.  The api was also missing from env.js and I had to enter that manually

**Comment by gbochenek** [comment]
Thanks for the notes @tmatinde!

I haven't gotten a chance to upgrade the tool to 2.5 yet, but if you have a fix for this, we would certainly love a pull request.

**Comment by tmatinde** [comment]
@gbochenek client also tried it in 2.3 and had the same problem. My easy fix was to copy the 2 js files into the directory.

**Comment by gbochenek** [comment]
@tmatinde Pull request #39 should fix this issue.  I'm going to push a release later today, but would you be able to test your 2.5 app with master?

Thanks!
