### ISSUE TITLE
Jimu.js  Error No OnScreenWidgetIcon.js & WidgetPlaceHolder.js WAB v2.6

### ISSUE THREAD

**Issue by mlewis22** [gbochenek/esri-wab-build#38]
I'm getting script errors when accessing the built app. Adding OnScreenWidgetIcon.js & WidgetPlaceHolder.js to the jimu.js folder (from the builder) in the app solves the issue. Maybe something missing in the build process to minify those files? 

![image](https://user-images.githubusercontent.com/9336379/34798055-6f4bd128-f652-11e7-9171-7301a6e597e0.png)

**Comment by gbochenek** [comment]
This should be fixed with your latest pull request #39
