### ISSUE TITLE
404 Errors when loading the built app

### ISSUE THREAD

**Issue by crackernutter** [gbochenek/esri-wab-build#4]
After the build process completes, I copy ./buildOutput/app into my webserver.  
I've run into a couple issues:

When I try to load the application, the loading screen spinner shows.  I get a bunch of 404 errors in the console:
/jsapi/jsapi/dojo/resources/dojo.css
/jsapi/jsapi/dijit/themes/claro/claro.css
https://gisdev.eon.faa.gov/jsapi/jsapi/esri/css/esri.css
jsapi/jsapi/dojox/layout/resources/ResizeHandle.css
/jsapi/jsapi/init.js

The application is looking for these resources at the root of my webserver, not the root of the app.  That being said, I don't see a jspai folder anywhere.  In the buildOutput folder there is an app-packages folder which seems to have the correct resources, except init.js, which is in the root of the app folder.  

To get around this, I uncommented the apiUrl in env.js, which seems to load the resources.  But you may want to uncomment that from the getgo or include it in the documentation if you don't have the API hosted at the root of your webserver...

However, now I'm getting a bunch of init.js errors (the app is now loading init.js from Esri's CDN, and the first error is 
Cannot read property 'en-us' of undefined: init.js:113....

Thoughts?

**Comment by gbochenek** [comment]
Which version of Web App Builder are you using?

Most JSAPI files should be loaded internally, but at this version its still taking some of the resources from the CDN.  If the API version is different than developed for, the find and replace won't work correctly.

**Comment by crackernutter** [comment]
Thanks!

I'm using the most recent version, version 2.4 - 

However, the errors change based on where   Ultimately, two directories are created when running this tool: buildOutput and build-src.  Inside buildOutput there is an app folder and an app-packages folder.  If I want to deploy this new built application on my webserver, what folders do I need to use.  Just the app?  The app folder in buildOuptut?  The entire buildOutput folder?  Can I rename them?

I'm getting a couple different errors based on where I put the folder.  Most recently, I'm getting a couple multipleDefine errors.  

It would be best to know the intended behavior (ie - what to do with the biuldOutput and build-src folders, and then I can more accurately troubleshoot the errors.  

Also, thanks so much for this functionality - we use WebAppBuilder apps a good bit, including some custom widgets, and the improved performance will be great once I iron out the issues.

**Comment by g3r4n** [comment]
The following link should solve your issue : 
[https://developers.arcgis.com/web-appbuilder/sample-code/change-url-of-arcgis-api-for-javascript.htm](https://developers.arcgis.com/web-appbuilder/sample-code/change-url-of-arcgis-api-for-javascript.htm)

Quick fix : 
In the buildOutput\app\env.js uncomment line 98

```
  apiUrl = '//js.arcgis.com/3.20';
```

**Comment by gbochenek** [comment]
I think this rolls into #10 for WAB 2.4 support.
