### ISSUE TITLE
Dojox Gauges are not Included

### ISSUE THREAD

**Issue by gbochenek** [gbochenek/esri-wab-build#47]
Dojox Gauges are not being included into our layer files.  Check for Dashboard theme before building them out?

**Comment by Biboba** [comment]
Hi,

I am having the same error as there:
https://github.com/steveoh/grunt-esri-slurp/issues/38

That is to say:

> error(311) Missing dependency. module: esri/dijit/_ObliqueRotationWidget; dependency: dojox/dgauges/CircularGauge
error(311) Missing dependency. module: esri/dijit/_ObliqueRotationWidget; dependency: dojox/dgauges/CircularRangeIndicator
error(311) Missing dependency. module: esri/dijit/_ObliqueRotationWidget; dependency: dojox/dgauges/LinearScaler
error(311) Missing dependency. module: esri/dijit/ObliqueViewer/OVCircularScale; dependency: dojox/dgauges/CircularScale
error (311) Missing dependency. module: esri/dijit/ObliqueViewer/OVCircularValueIndicator; dependency: dojox/dgauges/ScaleIndicatorBase


As suggested on the above link, I tried adding the following to the _app.config.js file but it did not solve the issue:
`map: {
    '*':  { 'dojox/dgauges': 'dgauges'}
}`

Any idea ?

Thanks !

**Comment by Biboba** [comment]
OK. Will have a look at it, thanks.
I don't understand though why is it bundled if it is not used in the app ?

**Comment by Biboba** [comment]
For reference, here are the changes that were made for [esri-slurp-example](https://github.com/tomwayson/esri-slurp-example) project:
https://github.com/tomwayson/esri-slurp-example/commit/673d98859ed76496b2c50b98693aeafaeceaf159

**Comment by gavinr** [comment]
@Biboba Thanks for posting that example. I had a question though: in the example, why are you including a reference to the `dgauges` fork ( `https://github.com/dmandrioli/dgauges.git`) instead of the "official" repo (`https://github.com/dojo/dgauges`)?

**Comment by Biboba** [comment]
I was just referencing the commit for information.
I believe you should ask @tomwayson !

**Comment by tomwayson** [comment]
If the issue involves dojo, bower, and/or grunt, you should most definitely **not** ask me... at least, not if you want any useful information. 😄

**Comment by gbochenek** [comment]
@gavinr Is #63 verified to fix this issue?  If so, feel free to close.
