### ISSUE TITLE
Refused to execute script

### ISSUE THREAD

**Issue by frq0224** [gbochenek/esri-wab-build#49]
Refused to execute script from 'http://localhost:52764/wab-app-build-script/buildOutput/app/jimu.js/OnScreenWidgetIcon.js?wab_dv=2.5' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
Refused to execute script from 'http://localhost:52764/wab-app-build-script/buildOutput/app/jimu.js/OnScreenWidgetIcon.js?wab_dv=2.5' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

**Comment by gbochenek** [comment]
The server determines MIME type, so shouldn't be any consequence of this tool.
