### ISSUE TITLE
broken on WAB 2.9 and up

### ISSUE THREAD

**Issue by kevinsagis** [gbochenek/esri-wab-build#58]
This tool holds great promise. WAB can be very slow to load on older machines due to its complexity and I've heard of great results from this tool.

However:
-Does not work with a WAB DE 2.9 or 2.10 app  (esri TS confirmed)

- Does not work with WAB 2.9 and env.js set to use API version 3.26.  I need to use 3.26 with the WAB 2.9 because of a serious bug I noted in WAB 2.9 that was fixed with API 3.26.  https://community.esri.com/thread/220202-bug-feature-popup-outline-is-mis-shapen-in-arcgis-online

Can it be updated to work with 2.9+ and to work with 2.9 on 3.26 API?

I even suggested on Esri forum they incorporate your script here officially. https://community.esri.com/ideas/15669-build-for-wab-doesnt-work-not-official-product-from-esri

Thank you! 

Kevin

**Comment by gbochenek** [comment]
Thanks @kevinsagis ! I'm glad to hear of the feedback.   I have a couple of colleagues that have gotten the tool working at 2.9 and am going to look at rolling their code into master over the next couple of weeks.  It would be great if you could help us testing at the later versions!

We will be tracking any updates and notes on Issue #55 .

**Comment by kevinsagis** [comment]
Hi George,

Thanks!!! Would love to help test.  Thank you again for releasing such a great tool and providing very thorough documentation.

Most important is I’ll have to use 3.26 API as noted, to correct for the severe popup bug I found in 3.25 / they fixed at 3.26. Do you think it will work with env.js set to one version ahead of the WAB?

Best,
Kevin

**Comment by gbochenek** [comment]
No guarantees on everything working with the version dump, but the build tool grabs the API version from env.js, so its worth a shot.
