### ISSUE TITLE
Directions widget improvement

### ISSUE THREAD

**Issue by karmstro77** [gbochenek/esri-wab-build#81]
When using the directions widget, it is not possible to save a route to the current map. I can save it to a Route Layer in my content but the Add Data widget does not recognize route layers. It would be great if the user could save the route to a feature service in the web app, similar to how the ERG and Bomb Blast widgets can write data to an existing layer (or new layer). We need this ability to save the route so users can buffer the route to find incidents within a certain distance using the Situational Awareness widget.

**Comment by rsjones** [comment]
If you have ideas for products they should be submitted via ArcGIS Ideas https://community.esri.com/t5/custom/page/page-id/arcgis-ideas
